### ISSUE TITLE
Added server but not showing

### ISSUE THREAD

**Issue by zawilliams** [wrklst/pulse-remote-server#1]
Hey @tobiasvielmetter - dope package. Thanks for creating it! I think this is just what I need for monitoring other servers on Forge that aren't running PHP (my db, cache and meilisearch servers).

I can't seem to get the other servers to show though. Can you let me know if there is anything obvious I'm missing?

I've added this to my `pulse.php` config and deployed the changes:

```php
'recorders' => [
        \WrkLst\Pulse\RemoteServer\Recorders\RemoteServers::class => [
            'server_name' => "database-production",
            'server_ssh' => "ssh forge@x.x.x.x", // I've tried both the private IP and public IP
            'query_interval' => 15,
            'directories' => explode(':', env('PULSE_SERVER_DIRECTORIES', '/')),
        ],
...
],
```

I've added `php artisan pulse:restart` to the deployment script for the 2 app servers and 1 worker server I have setup. The Pulse daemon is running (i.e. `php artisan pulse:check`).

<img width="526" alt="Screenshot 2024-05-10 at 12 11 17 AM" src="https://github.com/wrklst/pulse-remote-server/assets/1509011/f667d04a-82e2-44e3-9c58-ffe018c62c22">

I've enabled "Can connect to: `database-production`" from `app-1-production`, `app-2-production` and `worker-1-production` and inversely have enabled "Can connect to: `app-1-production`, `app-2-production` and `worker-1-production`" from `database-production` (though I don't think that is necessary).

I'm expecting to see an additional `database-production` server listed under the 3 that are there.

I've ssh'd into `app-1-production` and then ssh'd into `database-production` just to make sure things connect that way, and all seems fine.

Anything I'm doing wrong/missing?

**Comment by tobiasvielmetter** [comment]
@zawilliams Thanks for trying out the package. Your configuration looks good to me. I ma using the public IP, but as long as the ssh from you app server to your db server works password-less with the keys setup, either should work fine. Internal IP might be faster depending on your network setup for sure.
Did you add the package via composer? Did you check the error log for pulse? Maybe restart php on your production server, in case opCache is running to make sure the most current code is loaded. Maybe also try to empty your config cache, since the recorders are loaded through the config. 

Since you don't talk about any obvious errors on the pulse interface, I am assuming your pulse does not yet know about the config / the pulse remote server recorder. Let me know how it goes. The package runs for me in production stable since a while, so it definitely works.

My best,
Tobias

**Comment by zawilliams** [comment]
@tobiasvielmetter thanks for the response. I figured it out.

I missed that the `pulse:check` daemon was logging a `Permission denied (publickey).` on one server and `Host key verification failed.` on another. I was checking in regular logs. I assumed checking the checkbox for "Can connect to" in Forge was enough, but it seems I have to manually add the app-1, app-2, worker-1 public keys to the database server for it to connect. Once I did that, I saw the database server show up in Pulse.

Thanks again. Closing.
